name: almely_randevu
description: "Türkiye'nin Tek Nokta Randevu Portalı - almely_randevu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  geolocator: ^13.0.2
  geocoding: ^3.0.0
  http: ^1.6.0
  cupertino_icons: ^1.0.9
  google_maps_flutter: ^2.16.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/AlmEly.png