name: almely_super_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # Material simgelerini kullanabilmek için bu true kalmalı
  uses-material-design: true

  # Logonun uygulamada görünmesi için gereken kısım:
  assets:
    - assets/AlmEly.png

  # İleride özel yazı tipi eklemek istersen burayı kullanacağız
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf